version: "3.7"

services:
  v2ray:
    image: v2ray/official:latest
    restart: always
    volumes:
      - type: bind
        source: /home/DockerCompose_v2ray/client/config.json
        target: /etc/v2ray/config.json
    ports:
      - "1080:1080"
    command: ["v2ray", "-config=/etc/v2ray/config.json"]